services:
  # Backend Service (FastAPI)
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    port: 8000  # Backend runs on port 8000

  # Frontend Service (Streamlit)
  - type: web
    name: streamlit-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend.py --server.port 8501 --server.address=0.0.0.0
    port: 8501  # Frontend runs on port 8501
